server:
  port: 7070

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.andall.sally.supply.entity
  config-location: classpath:mybatis-config.xml

spring:
  datasource:
    url: jdbc:mysql://dbdev.dnatime.com:3306/shop_user?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: zm_shopuser
    password: 9d6x8VIr0GYwMb95
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    database: 0
    host: redistest.dnatime.com
    port: 6379
    password: ReayHs2WMVtn0KalCA0v
    timeout: 5000

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    #开启ACK
    listener:
      simple:
        acknowledge-mode: manual
